"use client";
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {Phone,ArrowLeftRight} from 'lucide-react';
import {LoadMore} from './load-more';
type Summary={calls:{total:number;voice:number;video:number;completed:number;incoming:number;outgoing:number;duration_seconds:number;known_duration:number;inferred_type:number};money:{total:number;transfer:number;red_packet:number;unknown_amount:number;unknown_direction:number;currencies:Record<string,{in:number;out:number}>};snapshot_at?:string};
type Row={account_id:string;external_id:string;occurred_at?:string;content:{media_type?:string;media_type_confidence?:string;direction?:string;status_label?:string;duration_seconds?:number|null;kind?:string;amount_minor?:number|null;currency?:string;counterparty?:string;initiator?:string;memo?:string;settled_at?:number;direction_source?:string}};
const amount=(minor:number|null|undefined,currency?:string)=>minor==null?'金额未保留':`${(minor/100).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2})} ${currency||'币种未记录'}`;
const duration=(seconds:number)=>`${Math.floor(seconds/3600)}:${String(Math.floor(seconds%3600/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;
const date=(value?:string|number)=>value==null?'未记录':new Date(typeof value==='number'?value*1000:value).toLocaleString('zh-CN',{dateStyle:'medium',timeStyle:'short'});
function useSummary(profileId:string){const [data,setData]=useState<Summary|null>(null),[error,setError]=useState(false),[retry,setRetry]=useState(0);useEffect(()=>{const abort=new AbortController();setData(null);setError(false);fetch(`/api/v1/profiles/${profileId}/contact-events/summary`,{signal:abort.signal}).then(r=>{if(!r.ok)throw Error();return r.json()}).then(setData).catch(e=>{if(e.name!=='AbortError')setError(true)});return()=>abort.abort()},[profileId,retry]);return {data,error,retry:()=>setRetry(n=>n+1)}}
export function ContactEventSidebar({profileId}:{profileId:string}){
 const {data,error,retry}=useSummary(profileId);
 return <section className="sidebar-section contact-event-sidebar"><h2>通话与收支</h2>{error?<button className="sidebar-add" onClick={retry}>重试读取</button>:!data?<p className="muted">读取记录…</p>:<><Link href={`/profiles/${profileId}?tab=contact-events&kind=call`}><Phone size={15}/><span>微信通话<small>{data.calls.voice} 语音 · {data.calls.video} 视频</small></span><b>{data.calls.total}</b></Link><Link href={`/profiles/${profileId}?tab=contact-events&kind=money`}><ArrowLeftRight size={15}/><span>金钱往来<small>{data.money.transfer} 转账 · {data.money.red_packet} 红包</small></span><b>{data.money.total}</b></Link>{Object.entries(data.money.currencies).map(([currency,totals])=><p key={currency}><span>收到 {amount(totals.in,currency)}</span><span>支出 {amount(totals.out,currency)}</span></p>)}<small>已知金额分别统计</small></>}</section>;
}
export function ContactEvents({profileId,kind='call'}:{profileId:string;kind?:string}){
 const selected=kind==='money'?'money':'call';const {data,error,retry}=useSummary(profileId);const [rows,setRows]=useState<Row[]>([]),[busy,setBusy]=useState(false),[failed,setFailed]=useState(false),[more,setMore]=useState(false);const request=useRef<AbortController|null>(null);
 async function load(offset=0){if(offset&&busy)return;request.current?.abort();const abort=new AbortController();request.current=abort;setBusy(true);setFailed(false);try{const r=await fetch(`/api/v1/profiles/${profileId}/contact-events?kind=${selected}&offset=${offset}`,{signal:abort.signal});if(!r.ok)throw Error();const next:Row[]=await r.json();if(abort.signal.aborted)return;setRows(old=>offset?[...old,...next]:next);setMore(next.length===30)}catch{if(!abort.signal.aborted)setFailed(true)}finally{if(!abort.signal.aborted)setBusy(false)}}
 useEffect(()=>{setRows([]);setMore(false);void load();return()=>request.current?.abort()},[profileId,selected]);
 const c=data?.calls,m=data?.money;
 return <section className="panel profile-card contact-events"><div className="panel-heading"><h2>{selected==='call'?'微信音视频通话':'微信金钱往来'}</h2><div className="provider-tabs">{[['call','通话'],['money','收支']].map(([k,label])=><Link className={selected===k?'selected':''} href={`/profiles/${profileId}?tab=contact-events&kind=${k}`} key={k}>{label}</Link>)}</div></div>{error?<button onClick={retry}>重试统计</button>:data&&<>{selected==='call'&&c?<><div className="chat-overview-numbers"><div><b>{c.voice}</b><span>语音通话</span></div><div><b>{c.video}</b><span>视频通话</span></div><div><b>{c.completed}</b><span>已接通 / 结束</span></div><div><b>{duration(c.duration_seconds)}</b><span>{c.known_duration} 次已知时长</span></div></div><p className="muted">收到 {c.incoming} 次 · 呼出 {c.outgoing} 次{c.inferred_type>0&&` · ${c.inferred_type} 次媒体类型根据记录推断`}</p></>:m&&<><div className="chat-overview-numbers"><div><b>{m.total}</b><span>条往来</span></div><div><b>{m.transfer}</b><span>转账 · {m.red_packet} 个红包</span></div>{Object.entries(m.currencies).map(([currency,totals])=><div key={currency}><b>{amount(totals.in,currency)}</b><span>收到 · 支出 {amount(totals.out,currency)}</span></div>)}</div><p className="muted">{m.unknown_amount} 条未保留金额 · {m.unknown_direction} 条方向未知。按已知金额分别统计，不折算为欠款余额。</p></>}{data.snapshot_at&&<p className="record-scope">归档于 {date(data.snapshot_at)}</p>}</>}
 <div className="contact-event-table"><table><thead><tr><th>时间</th><th>类型</th><th>方向</th><th>{selected==='call'?'时长':'金额'}</th><th>状态</th>{selected==='money'&&<><th>对方 / 来源</th><th>到账时间</th><th>备注</th></>}</tr></thead><tbody>{rows.map(row=>{const r=row.content;return <tr key={`${row.account_id}:${row.external_id}`}><td>{date(row.occurred_at)}</td><td>{selected==='call'?`${r.media_type==='video'?'视频':'语音'}${r.media_type_confidence!=='high'?'（推断）':''}`:r.kind==='red_packet'?'红包':'转账'}</td><td>{r.direction==='in'?(selected==='call'?'收到':'收入'):r.direction==='out'?(selected==='call'?'呼出':'支出'):'未知'}{selected==='money'&&r.direction&&['initiator','lifecycle'].includes(r.direction_source||'')&&<small>推断</small>}</td><td>{selected==='call'?(r.duration_seconds==null?'未保留':duration(r.duration_seconds)):amount(r.amount_minor,r.currency)}</td><td>{r.status_label||'未知'}</td>{selected==='money'&&<><td>{r.counterparty||'—'}</td><td>{r.settled_at?date(r.settled_at):'—'}</td><td>{r.memo||'—'}</td></>}</tr>})}</tbody></table></div>
 {failed&&<p role="alert">记录读取失败。<button onClick={()=>void load(rows.length)}>重试</button></p>}{busy&&<p role="status">正在读取记录…</p>}{!busy&&!failed&&!rows.length&&<p className="muted">尚未收录此类记录。</p>}{more&&<LoadMore cursor={rows.at(-1)?.external_id||''} busy={busy} error={failed} onLoad={()=>void load(rows.length)} label="加载更早的记录"/>}
 </section>;
}
