"use client";
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {Phone,ArrowLeftRight} from 'lucide-react';
import {LoadMore} from './load-more';
type Summary={calls:{total:number;voice:number;video:number;completed:number;incoming:number;outgoing:number;duration_seconds:number;known_duration:number;inferred_type:number};money:{total:number;transfer:number;red_packet:number;unknown_amount:number;unknown_direction:number;currencies:Record<string,{in:number;out:number}>};snapshot_at?:string};
type Row={account_id:string;external_id:string;occurred_at?:string;content:{media_type?:string;media_type_confidence?:string;direction?:string;status_label?:string;duration_seconds?:number|null;kind?:string;amount_minor?:number|null;currency?:string;counterparty?:string;initiator?:string;memo?:string;settled_at?:number;direction_source?:string}};
const amount=(minor:number|null|undefined,currency?:string)=>minor==null?'Amount not kept':`${(minor/100).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})} ${currency||'currency not recorded'}`;
const duration=(seconds:number)=>`${Math.floor(seconds/3600)}:${String(Math.floor(seconds%3600/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;
const date=(value?:string|number)=>value==null?'Not recorded':new Date(typeof value==='number'?value*1000:value).toLocaleString('en-US',{dateStyle:'medium',timeStyle:'short'});
function useSummary(profileId:string){const [data,setData]=useState<Summary|null>(null),[error,setError]=useState(false),[retry,setRetry]=useState(0);useEffect(()=>{const abort=new AbortController();setData(null);setError(false);fetch(`/api/v1/profiles/${profileId}/contact-events/summary`,{signal:abort.signal}).then(r=>{if(!r.ok)throw Error();return r.json()}).then(setData).catch(e=>{if(e.name!=='AbortError')setError(true)});return()=>abort.abort()},[profileId,retry]);return {data,error,retry:()=>setRetry(n=>n+1)}}
export function ContactEventSidebar({profileId}:{profileId:string}){
 const {data,error,retry}=useSummary(profileId);
 return <section className="sidebar-section contact-event-sidebar"><h2>Calls and money</h2>{error?<button className="sidebar-add" onClick={retry}>Retry loading</button>:!data?<p className="muted">Loading records…</p>:<><Link href={`/profiles/${profileId}?tab=contact-events&kind=call`}><Phone size={15}/><span>WeChat calls<small>{data.calls.voice} voice · {data.calls.video} video</small></span><b>{data.calls.total}</b></Link><Link href={`/profiles/${profileId}?tab=contact-events&kind=money`}><ArrowLeftRight size={15}/><span>Money transfers<small>{data.money.transfer} transfers · {data.money.red_packet} red packets</small></span><b>{data.money.total}</b></Link>{Object.entries(data.money.currencies).map(([currency,totals])=><p key={currency}><span>Received {amount(totals.in,currency)}</span><span>Sent {amount(totals.out,currency)}</span></p>)}<small>Known amounts counted separately</small></>}</section>;
}
export function ContactEvents({profileId,kind='call'}:{profileId:string;kind?:string}){
 const selected=kind==='money'?'money':'call';const {data,error,retry}=useSummary(profileId);const [rows,setRows]=useState<Row[]>([]),[busy,setBusy]=useState(false),[failed,setFailed]=useState(false),[more,setMore]=useState(false);const request=useRef<AbortController|null>(null);
 async function load(offset=0){if(offset&&busy)return;request.current?.abort();const abort=new AbortController();request.current=abort;setBusy(true);setFailed(false);try{const r=await fetch(`/api/v1/profiles/${profileId}/contact-events?kind=${selected}&offset=${offset}`,{signal:abort.signal});if(!r.ok)throw Error();const next:Row[]=await r.json();if(abort.signal.aborted)return;setRows(old=>offset?[...old,...next]:next);setMore(next.length===30)}catch{if(!abort.signal.aborted)setFailed(true)}finally{if(!abort.signal.aborted)setBusy(false)}}
 useEffect(()=>{setRows([]);setMore(false);void load();return()=>request.current?.abort()},[profileId,selected]);
 const c=data?.calls,m=data?.money;
 return <section className="panel profile-card contact-events"><div className="panel-heading"><h2>{selected==='call'?'WeChat voice and video calls':'WeChat money transfers'}</h2><div className="provider-tabs">{[['call','Calls'],['money','Money']].map(([k,label])=><Link className={selected===k?'selected':''} href={`/profiles/${profileId}?tab=contact-events&kind=${k}`} key={k}>{label}</Link>)}</div></div>{error?<button onClick={retry}>Retry totals</button>:data&&<>{selected==='call'&&c?<><div className="chat-overview-numbers"><div><b>{c.voice}</b><span>Voice calls</span></div><div><b>{c.video}</b><span>Video calls</span></div><div><b>{c.completed}</b><span>Completed / ended</span></div><div><b>{duration(c.duration_seconds)}</b><span>{c.known_duration} with known duration</span></div></div><p className="muted">{c.incoming} incoming · {c.outgoing} outgoing{c.inferred_type>0&&` · ${c.inferred_type} media types inferred from the record`}</p></>:m&&<><div className="chat-overview-numbers"><div><b>{m.total}</b><span>transfers</span></div><div><b>{m.transfer}</b><span>Transfers · {m.red_packet} red packets</span></div>{Object.entries(m.currencies).map(([currency,totals])=><div key={currency}><b>{amount(totals.in,currency)}</b><span>Received · sent {amount(totals.out,currency)}</span></div>)}</div><p className="muted">{m.unknown_amount} without a kept amount · {m.unknown_direction} with unknown direction. Known amounts are counted separately, not as a running balance.</p></>}{data.snapshot_at&&<p className="record-scope">Archived {date(data.snapshot_at)}</p>}</>}
 <div className="contact-event-table"><table><thead><tr><th>Time</th><th>Type</th><th>Direction</th><th>{selected==='call'?'Duration':'Amount'}</th><th>Status</th>{selected==='money'&&<><th>Counterparty / source</th><th>Settled</th><th>Memo</th></>}</tr></thead><tbody>{rows.map(row=>{const r=row.content;return <tr key={`${row.account_id}:${row.external_id}`}><td>{date(row.occurred_at)}</td><td>{selected==='call'?`${r.media_type==='video'?'Video':'Voice'}${r.media_type_confidence!=='high'?' (inferred)':''}`:r.kind==='red_packet'?'Red packet':'Transfer'}</td><td>{r.direction==='in'?(selected==='call'?'Incoming':'Received'):r.direction==='out'?(selected==='call'?'Outgoing':'Sent'):'Unknown'}{selected==='money'&&r.direction&&['initiator','lifecycle'].includes(r.direction_source||'')&&<small>Inferred</small>}</td><td>{selected==='call'?(r.duration_seconds==null?'Not kept':duration(r.duration_seconds)):amount(r.amount_minor,r.currency)}</td><td>{r.status_label||'Unknown'}</td>{selected==='money'&&<><td>{r.counterparty||'—'}</td><td>{r.settled_at?date(r.settled_at):'—'}</td><td>{r.memo||'—'}</td></>}</tr>})}</tbody></table></div>
 {failed&&<p role="alert">Could not load records. <button onClick={()=>void load(rows.length)}>Retry</button></p>}{busy&&<p role="status">Loading records…</p>}{!busy&&!failed&&!rows.length&&<p className="muted">No records of this kind yet.</p>}{more&&<LoadMore cursor={rows.at(-1)?.external_id||''} busy={busy} error={failed} onLoad={()=>void load(rows.length)} label="Load earlier records"/>}
 </section>;
}
