"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {apiFetch} from "../lib/api";
type Candidate={id:string;provider:string;external_id:string;username?:string;source_profile_id:string;candidate_profile_id:string;candidate_display_name:string;evidence:unknown};
export function IdentityReview(){
 const [rows,setRows]=useState<Candidate[]>([]),[confirming,setConfirming]=useState<string|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
 async function load(){const r=await fetch('/api/v1/identity-candidates');if(r.ok)setRows(await r.json());else setError("Could not load identity candidates.");}
 useEffect(()=>{void load();},[]);
 async function decide(row:Candidate,action:'accept'|'reject'){setBusy(true);setError("");try{const r=await apiFetch(`/api/v1/identity-candidates/${row.id}/${action}`,{method:'POST'});if(!r.ok)throw new Error();setConfirming(null);await load();}catch{setError("The review was not saved. Check the candidate and try again.");}finally{setBusy(false);}}
 return <section className="panel import-panel"><div className="panel-heading"><h2>Identity matches to review</h2></div><p className="muted">Accounts, posts, and relationships move only after you confirm they are the same person. Matching names do not merge automatically.</p>{error&&<p role="alert">{error}</p>}{!rows.length&&<p className="muted">Nothing waiting for review. Source accounts stay separate.</p>}{rows.map(row=><article className="candidate-card" key={row.id}><p><Link href={`/profiles/${row.source_profile_id}`}>{row.provider} · {row.username||row.external_id}</Link><span> → </span><Link href={`/profiles/${row.candidate_profile_id}`}>{row.candidate_display_name}</Link></p><details><summary>Show source evidence</summary><pre>{JSON.stringify(row.evidence,null,2)}</pre></details>{confirming===row.id?<div><p>Confirm these profiles are the same person and merge the source into “{row.candidate_display_name}”?</p><button className="button button-primary" disabled={busy} onClick={()=>void decide(row,'accept')}>Confirm merge</button><button className="button button-soft" onClick={()=>setConfirming(null)}>Cancel</button></div>:<div className="edit-panel-actions"><button className="button button-soft" disabled={busy} onClick={()=>void decide(row,'reject')}>Not the same person</button><button className="button button-primary" disabled={busy} onClick={()=>setConfirming(row.id)}>Review and confirm</button></div>}</article>)}</section>;
}
