"use client";
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {MapPinned} from 'lucide-react';
import type {Map as LeafletMap} from 'leaflet';
import 'leaflet/dist/leaflet.css';
type Point={label:string;latitude:number;longitude:number;count:number;sources:string[];source_kind:string;precision:string;people_count:number;people:{id:string;name:string}[];events:{at:string;text:string;source:string;url:string}[]};
type Atlas={points:Point[];people:number;place_count:number;located_records:number;post_records:number;profile_records:number;years:number[];unresolved:{label:string;count:number;sources:string[];people:{id:string;name:string}[]}[]};
export function LocationAtlas(){
 const root=useRef<HTMLElement>(null),[visible,setVisible]=useState(false),[provider,setProvider]=useState(''),[year,setYear]=useState(''),[kind,setKind]=useState('all'),[data,setData]=useState<Atlas|null>(null),[error,setError]=useState(false),[attempt,setAttempt]=useState(0),[busy,setBusy]=useState(false),[query,setQuery]=useState(''),[selected,setSelected]=useState<Point|null>(null);
 useEffect(()=>{const observer=new IntersectionObserver(entries=>{if(entries.some(e=>e.isIntersecting)){setVisible(true);observer.disconnect()}},{rootMargin:'350px'});if(root.current)observer.observe(root.current);return()=>observer.disconnect()},[]);
 useEffect(()=>{if(!visible)return;const abort=new AbortController();setBusy(true);setError(false);setSelected(null);const p=new URLSearchParams({kind});if(provider)p.set('provider',provider);if(year)p.set('year',year);fetch(`/api/v1/metrics/locations?${p}`,{signal:abort.signal}).then(r=>{if(!r.ok)throw Error();return r.json()}).then(setData).catch(e=>{if(e.name!=='AbortError')setError(true)}).finally(()=>{if(!abort.signal.aborted)setBusy(false)});return()=>abort.abort()},[visible,provider,year,kind,attempt]);
 const [searchResults,setSearchResults]=useState(false);const results=(data?.points||[]).filter(p=>(p.label+' '+p.people.map(p=>p.name).join(' ')).toLocaleLowerCase().includes(query.toLocaleLowerCase()));
 return <section ref={root} className="panel profile-card global-atlas" aria-label="Places for everyone"><div className="panel-heading"><div><h2><MapPinned size={18}/>Places for everyone</h2><p className="muted">Post traces and profile cities are marked separately. Profile cities sit on a city center, not a live location.</p></div></div><div className="map-filters"><label>Source<select aria-label="Source" value={provider} onChange={e=>setProvider(e.target.value)}><option value="">All sources</option><option value="wechat">WeChat</option><option value="instagram">Instagram</option><option value="linkedin">LinkedIn</option></select></label><label>Place type<select aria-label="Place type" value={kind} onChange={e=>setKind(e.target.value)}><option value="all">All</option><option value="profile">Profile city</option><option value="post">Post trace</option></select></label><label>Year<select aria-label="Year" value={year} disabled={kind==='profile'} onChange={e=>setYear(e.target.value)}><option value="">All years</option>{data?.years.map(y=><option key={y}>{y}</option>)}</select></label><label>Find a place<input value={query} onChange={e=>{setQuery(e.target.value);setSearchResults(true)}} type="search" placeholder="City or person…"/></label></div>
 {error?<p role="alert">Could not load the map. <button className="button button-soft" onClick={()=>setAttempt(n=>n+1)}>Retry</button></p>:!data?<p role="status">{visible?'Collecting places…':'Scroll to see the world map'}</p>:<><div className="atlas-counts"><span><b>{data.people.toLocaleString()}</b> people with a place</span><span><b>{data.place_count.toLocaleString()}</b> places</span><span>{data.profile_records.toLocaleString()} profile cities · {data.post_records.toLocaleString()} post traces</span>{busy&&<small role="status">Updating map…</small>}</div><WorldMap points={data.points} selected={selected} onSelect={setSelected}/><div className="map-legend"><span>● WeChat</span><span>● Instagram</span><span>● LinkedIn</span><small>Numbers in circles are clustered places · click to zoom</small></div>
 {query&&searchResults&&<div className="atlas-search-results">{results.slice(0,30).map((p,i)=><button key={i} onClick={()=>{setSelected(p);setSearchResults(false)}}>{p.label} · {p.people_count} people · {p.source_kind==='profile'?'profile city':'post trace'}</button>)}{!results.length&&<span>No matching located places.</span>}</div>}
 {selected&&<div className="atlas-selection"><h3>{selected.label}</h3><p>{selected.source_kind==='profile'?'Profile city center · GeoNames':selected.source_kind==='mixed'?'Profile cities and post traces in this area':'Post coordinates'} · {selected.people_count} people · {selected.count} records</p><div className="atlas-people">{selected.people.map(p=><Link key={p.id} href={`/profiles/${p.id}`}>{p.name} ↗</Link>)}</div>{selected.source_kind!=='profile'&&<div className="atlas-events">{selected.events.map((e,i)=><Link key={i} href={e.url}>{e.at.slice(0,10)} · {e.text} · open post</Link>)}</div>}{selected.people_count>selected.people.length&&<small>Showing {selected.people.length} of those people.</small>}</div>}
 <details className="unlocated"><summary>Profile places without a precise pin · {data.unresolved.length} text addresses</summary><p>Country, region, or ambiguous city names stay as written until they have a clear coordinate.</p><div>{data.unresolved.map(row=><article key={row.label}><strong>{row.label}</strong><span>{row.count} people</span><div>{row.people.map(p=><Link key={p.id} href={`/profiles/${p.id}`}>{p.name}</Link>)}</div></article>)}</div></details><p className="map-attribution">Profile cities use <a href="https://www.geonames.org/" target="_blank" rel="noreferrer">GeoNames</a> · <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noreferrer">CC BY 4.0</a>. Ambiguous city names are not auto-located.</p></>}
 </section>;
}
function WorldMap({points,selected,onSelect}:{points:Point[];selected:Point|null;onSelect:(p:Point)=>void}){
 const container=useRef<HTMLDivElement>(null),map=useRef<LeafletMap|null>(null),[ready,setReady]=useState(false);const callback=useRef(onSelect);callback.current=onSelect;
 useEffect(()=>{let canceled=false;let observer:ResizeObserver;import('leaflet').then(async L=>{if(canceled||!container.current)return;const instance=L.map(container.current,{minZoom:0,maxZoom:18,preferCanvas:true,scrollWheelZoom:false,worldCopyJump:true}).setView([22,0],1);map.current=instance;L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap'}).addTo(instance);observer=new ResizeObserver(()=>instance.invalidateSize());observer.observe(container.current);setReady(true);const land=await fetch('/vendor/world.geojson').then(r=>r.json()).catch(()=>null);if(!canceled&&land){instance.createPane('worldFallback').style.zIndex='150';L.geoJSON(land,{pane:'worldFallback',style:{color:'#9cbbb0',weight:.6,fillColor:'#e3edda',fillOpacity:1},interactive:false}).addTo(instance).bringToBack()}});return()=>{canceled=true;observer?.disconnect();map.current?.remove();map.current=null}},[]);
 useEffect(()=>{if(!ready||!map.current)return;let canceled=false;let cleanup=()=>{};import('leaflet').then(L=>{if(canceled||!map.current)return;const instance=map.current,layer=L.layerGroup().addTo(instance);function draw(){layer.clearLayers();const buckets=new Map<string,Point[]>();for(const p of points){const pixel=instance.project([p.latitude,p.longitude],instance.getZoom());const key=`${Math.floor(pixel.x/52)}:${Math.floor(pixel.y/52)}`;const group=buckets.get(key)||[];group.push(p);buckets.set(key,group)}for(const group of buckets.values()){const lat=group.reduce((n,p)=>n+p.latitude,0)/group.length,lon=group.reduce((n,p)=>n+p.longitude,0)/group.length;const p=group[0],multiple=group.length>1;const color=p.sources.includes('linkedin')?'#2465a9':p.sources.includes('instagram')?'#8e527b':'#147d73';const marker=L.circleMarker([lat,lon],{radius:multiple?Math.min(23,12+Math.log(group.length)*2):7,fillColor:color,fillOpacity:multiple?.8:.95,color:'white',weight:2});const title=document.createElement('span');title.textContent=multiple?String(group.length):p.label;marker.bindTooltip(title,multiple?{permanent:true,direction:'center',className:'atlas-cluster-label'}:{});marker.on('click',()=>{if(multiple&&instance.getZoom()>=16){const people=Array.from(new Map(group.flatMap(p=>p.people).map(p=>[p.id,p])).values());callback.current({...p,label:'Places in this area',people,people_count:people.length,events:group.flatMap(p=>p.events),count:group.reduce((n,p)=>n+p.count,0),source_kind:'mixed',sources:Array.from(new Set(group.flatMap(p=>p.sources)))})}else if(multiple)instance.fitBounds(L.latLngBounds(group.map(p=>[p.latitude,p.longitude])),{padding:[45,45],maxZoom:Math.min(18,instance.getZoom()+3)});else callback.current(p)});marker.addTo(layer)}}draw();instance.on('zoomend',draw);cleanup=()=>{instance.off('zoomend',draw);instance.removeLayer(layer)}});return()=>{canceled=true;cleanup()}},[points,ready]);
 useEffect(()=>{if(selected)map.current?.setView([selected.latitude,selected.longitude],10)},[selected,ready]);
 return <><div className="global-map-toolbar"><button className="button button-soft" onClick={()=>map.current?.setView([22,0],1)}>Show the world</button></div><div className="atlas-map global-atlas-map" ref={container} role="region" aria-label="World map of everyone. Click a cluster to zoom."/></>;
}
