"use client";
import Link from "next/link";
import {useEffect,useRef,useState} from "react";
import {LoadMore} from "./load-more";
import {apiFetch} from "../lib/api";
import {recordText} from "../lib/record-text";

type Person={id:string;display_name:string};
type RecordItem={id:string;activity_type:string;occurred_at:string;title:string;body?:string;source_type:string;state:string;due_at?:string;participants?:Person[]};
const kinds:Record<string,string>={note:"笔记",activity:"活动",task:"待办",reminder:"提醒",call:"通话",money:"金钱",wechat_call:"微信通话",wechat_money:"微信收支"};
const localDate=(value?:string)=>{const d=value?new Date(value):new Date();return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);};
export function RecordsView({profileId}:{profileId:string}){
 const request=useRef<AbortController|null>(null);
 const [loading,setLoading]=useState(false);
 const [rows,setRows]=useState<RecordItem[]>([]),[more,setMore]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const [editing,setEditing]=useState<string|null>(null),[kind,setKind]=useState("note"),[title,setTitle]=useState(""),[body,setBody]=useState(""),[at,setAt]=useState(localDate()),[due,setDue]=useState("");
 const [people,setPeople]=useState<Person[]>([]),[query,setQuery]=useState(""),[matches,setMatches]=useState<Person[]>([]);
 async function load(offset=0){
  if(offset&&loading)return;
  request.current?.abort();const abort=new AbortController();request.current=abort;setLoading(true);setError("");
  try{const r=await fetch(`/api/v1/activities?profile_id=${profileId}&limit=30&offset=${offset}`,{signal:abort.signal});if(!r.ok)throw new Error();const data:RecordItem[]=await r.json();if(abort.signal.aborted)return;setRows(old=>offset?[...old,...data.filter(row=>!old.some(item=>item.id===row.id))]:data);setMore(data.length===30);}
  catch{if(!abort.signal.aborted)setError("无法读取记录，请重试。");}finally{if(!abort.signal.aborted)setLoading(false);}
 }
 useEffect(()=>{setRows([]);setMore(false);void load();return()=>request.current?.abort();},[profileId]);
 useEffect(()=>{if(!query.trim()){setMatches([]);return;}const abort=new AbortController();const timer=setTimeout(()=>{fetch(`/api/v1/profiles?q=${encodeURIComponent(query)}&limit=8`,{signal:abort.signal}).then(r=>r.json()).then(setMatches).catch(()=>{});},250);return()=>{clearTimeout(timer);abort.abort();};},[query]);
 function edit(row?:RecordItem){setEditing(row?.id||"new");setKind(row?.activity_type||"note");setTitle(row?.title||"");setBody(row?.body||"");setAt(localDate(row?.occurred_at));setDue(row?.due_at?localDate(row.due_at):"");setPeople(row?.participants?.filter(p=>p.id!==profileId)||[]);setError("");}
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");try{const r=await apiFetch(editing==="new"?'/api/v1/activities':`/api/v1/activities/${editing}`,{method:editing==="new"?'POST':'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({activity_type:kind,title,body,occurred_at:new Date(at).toISOString(),due_at:due?new Date(due).toISOString():null,participant_profile_ids:[profileId,...people.map(p=>p.id)]})});if(!r.ok)throw new Error();setEditing(null);await load();}catch{setError("保存失败，内容仍保留在编辑框中。");}finally{setBusy(false);}}
 async function toggle(row:RecordItem){setBusy(true);try{const r=await apiFetch(`/api/v1/activities/${row.id}/state`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({state:row.state==='done'?'open':'done'})});if(!r.ok)throw new Error();await load();}catch{setError("无法更新完成状态。");}finally{setBusy(false);}}
 return <section className="panel profile-card records-panel"><div className="panel-heading"><div><h2>笔记与记录</h2><p className="muted">活动、通话、收支、待办和提醒。</p></div><button className="button button-primary" onClick={()=>edit()}>添加记录</button></div>{error&&<p role="alert">{error}</p>}
 {editing&&<form className="record-form" onSubmit={save}><label>记录类型<select value={kind} onChange={e=>setKind(e.target.value)}>{Object.entries(kinds).filter(([key])=>!key.startsWith('wechat_')).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>标题<input required maxLength={255} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>记录时间<input required type="datetime-local" value={at} onChange={e=>setAt(e.target.value)}/></label>{['task','reminder'].includes(kind)&&<label>到期时间<input type="datetime-local" value={due} onChange={e=>setDue(e.target.value)}/></label>}<label>内容<textarea rows={5} value={body} onChange={e=>setBody(e.target.value)}/></label><label>添加参与人<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索联系人并选择"/></label><div className="record-people">{people.map(p=><button type="button" className="button button-soft" key={p.id} onClick={()=>setPeople(old=>old.filter(x=>x.id!==p.id))}>{p.display_name} ×</button>)}{matches.filter(p=>p.id!==profileId&&!people.some(x=>x.id===p.id)).map(p=><button type="button" className="button button-soft" key={p.id} onClick={()=>{setPeople(old=>[...old,p]);setQuery("");}}>{p.display_name} ＋</button>)}</div>{kind==='reminder'&&<p className="muted">到期记录在此处标记；尚未连接邮件或系统推送。</p>}<div className="edit-panel-actions"><button type="button" className="button button-soft" onClick={()=>setEditing(null)}>取消</button><button className="button button-primary" disabled={busy}>{busy?'保存中…':'保存记录'}</button></div></form>}
 <div className="record-list">{rows.map(row=><article key={row.id}><header><span className="eyebrow">{kinds[row.activity_type]||'记录'}</span><time>{new Date(row.occurred_at).toLocaleDateString('zh-CN')}</time></header><h3>{row.title}</h3><p className="event-body">{recordText(row.body)}</p>{row.due_at&&<p className={row.state==='open'&&new Date(row.due_at)<new Date()?'form-error':'muted'}>到期：{new Date(row.due_at).toLocaleString('zh-CN')}</p>}<div className="record-people">{row.participants?.map(p=><Link href={`/profiles/${p.id}`} key={p.id}>{p.display_name}</Link>)}</div><div className="edit-panel-actions">{['task','reminder'].includes(row.activity_type)&&<button className="button button-soft" disabled={busy} onClick={()=>void toggle(row)}>{row.state==='done'?'已完成 · 重新打开':'标为完成'}</button>}{row.source_type==='manual'&&<button className="button button-soft" onClick={()=>edit(row)}>编辑记录</button>}</div></article>)}</div>{!rows.length&&!loading&&!error&&<p className="muted">尚无记录。</p>}{loading&&<p role="status">正在读取记录…</p>}{more&&<LoadMore cursor={rows.at(-1)?.id||""} busy={loading||!!editing} error={!!error} onLoad={()=>void load(rows.length)} label="加载更多记录"/>}{!!error&&!more&&<button className="button button-soft" onClick={()=>void load()}>重试</button>}</section>;
}
