"use client";
import {useEffect,useState} from "react";
import {apiFetch} from "../lib/api";
type Person={id:string;display_name:string;profile_type:string};
export function RelationshipEditor({profileId,onSaved}:{profileId:string;onSaved:()=>void}){
 const [open,setOpen]=useState(false),[query,setQuery]=useState(""),[matches,setMatches]=useState<Person[]>([]),[person,setPerson]=useState<Person|null>(null),[kind,setKind]=useState("朋友"),[note,setNote]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
 useEffect(()=>{if(!query.trim()){setMatches([]);return;}const abort=new AbortController();const timer=setTimeout(()=>fetch(`/api/v1/profiles?q=${encodeURIComponent(query)}&profile_type=person&limit=8`,{signal:abort.signal}).then(r=>r.json()).then(setMatches).catch(()=>{}),250);return()=>{clearTimeout(timer);abort.abort();};},[query]);
 async function save(e:React.FormEvent){e.preventDefault();if(!person)return;setBusy(true);setError("");try{const r=await apiFetch(`/api/v1/profiles/${profileId}/relationships`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({to_profile_id:person.id,relationship_type:kind,note})});if(!r.ok)throw new Error();setOpen(false);setPerson(null);setQuery("");onSaved();}catch{setError("关系未保存，请重试。");}finally{setBusy(false);}}
 return <div><button className="button button-soft" onClick={()=>setOpen(v=>!v)}>{open?'关闭添加':'添加关系'}</button>{open&&<form className="record-form" onSubmit={save}><label>选择联系人<input value={query} onChange={e=>{setQuery(e.target.value);setPerson(null);}} placeholder="搜索并确认具体的人"/></label><div className="record-people">{matches.filter(p=>p.id!==profileId).map(p=><button type="button" className="button button-soft" key={p.id} onClick={()=>{setPerson(p);setMatches([]);}}>{p.display_name}</button>)}</div>{person&&<p>已选择：{person.display_name}</p>}<label>关系类型<input required maxLength={120} value={kind} onChange={e=>setKind(e.target.value)} placeholder="如同事、同学、家人"/></label><label>备注<textarea value={note} onChange={e=>setNote(e.target.value)}/></label>{error&&<p role="alert">{error}</p>}<button className="button button-primary" disabled={busy||!person}>{busy?'保存中…':'确认关系'}</button></form>}</div>;
}
