"use client";
import {useEffect,useState} from 'react';
type Tag={id:string;name:string;people:number;sources:string[]};
const sourceName:Record<string,string>={wechat:'WeChat',manual:'Manual',monica:'Monica'};
export function TagFilter({profileType,selected,onSelect}:{profileType:string;selected:string;onSelect:(id:string)=>void}){
 const [tags,setTags]=useState<Tag[]>([]),[search,setSearch]=useState(''),[error,setError]=useState(false),[busy,setBusy]=useState(true),[attempt,setAttempt]=useState(0);
 useEffect(()=>{const abort=new AbortController();setBusy(true);setError(false);fetch(`/api/v1/tags${profileType==='all'?'':`?profile_type=${profileType}`}`,{signal:abort.signal}).then(r=>{if(!r.ok)throw Error();return r.json()}).then(setTags).catch(e=>{if(e.name!=='AbortError')setError(true)}).finally(()=>{if(!abort.signal.aborted)setBusy(false)});return()=>abort.abort()},[profileType,attempt]);
 const active=tags.find(t=>t.id===selected);const visible=tags.filter(t=>t.name.toLocaleLowerCase().includes(search.trim().toLocaleLowerCase()));
 return <section className="tag-browser" aria-label="Filter people by tag"><div className="tag-browser-heading"><h2>Browse by tag <small>{tags.length} tags</small></h2><label><span className="sr-only">Search tags</span><input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search tags…"/></label>{selected&&<button className="button button-soft" onClick={()=>onSelect('')}>Clear tag</button>}</div>{active&&<p className="active-tag">Showing “{active.name}” · {active.people} {profileType==='group'?'groups':'people'}</p>}{error?<p role="alert">Could not load tags. <button onClick={()=>setAttempt(n=>n+1)}>Retry</button></p>:<div className="tag-options">{visible.map(tag=><button aria-pressed={selected===tag.id} className={selected===tag.id?'selected':''} key={tag.id} onClick={()=>onSelect(selected===tag.id?'':tag.id)} title={tag.sources?.map(s=>sourceName[s]||s).join(', ')}><span>{tag.name}</span><b>{tag.people}</b></button>)}</div>}{busy&&<small role="status">Loading tags…</small>}{!busy&&!error&&!visible.length&&<p className="muted">{search?'No matching tags.':'No tags yet.'}</p>}</section>;
}
