"use client";
import {useEffect,useState} from 'react';
import {apiFetch} from '../lib/api';
export function TotpSettings(){
 const [enabled,setEnabled]=useState(false),[secret,setSecret]=useState(''),[code,setCode]=useState(''),[recovery,setRecovery]=useState<string[]>([]),[error,setError]=useState('');
 useEffect(()=>{fetch('/api/v1/auth/totp/status').then(r=>r.json()).then(x=>setEnabled(x.enabled)).catch(()=>setError('Could not load authenticator settings'))},[]);
 async function setup(){const r=await apiFetch('/api/v1/auth/totp/setup',{method:'POST'});const x=await r.json();if(r.ok)setSecret(x.secret);else setError(x.detail)}
 async function verify(){const r=await apiFetch('/api/v1/auth/totp/verify',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code})});const x=await r.json();if(r.ok){setEnabled(true);setSecret('');setRecovery(x.recovery_codes)}else setError('That code is not valid. Try again.')}
 return <section className="panel profile-card"><h2>Authenticator sign-in</h2><p>{enabled?'Two-factor authentication is on.':'Add a one-time code to sign-in. It turns on only after a successful check.'}</p>{!enabled&&!secret&&<button className="button button-soft" onClick={()=>void setup()}>Set up authenticator</button>}{secret&&<><p>Add this account in your authenticator with this secret:</p><code>{secret}</code><form onSubmit={e=>{e.preventDefault();void verify()}}><label>Authenticator code<input value={code} onChange={e=>setCode(e.target.value)} inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" required/></label><button className="button button-primary">Verify and enable</button></form></>}{recovery.length>0&&<div><h3>Save recovery codes</h3><p>Each code can be used once. This is the only time these codes are shown.</p><ul>{recovery.map(value=><li key={value}><code>{value}</code></li>)}</ul><button className="button button-soft" onClick={()=>setRecovery([])}>Saved · hide codes</button></div>}{error&&<p role="alert">{error}</p>}</section>
}
